# Header
menu:
  The Camp: /the-camp
  Speakers: /speakers
  Sponsors: /sponsors
  Organisers: /organisers
  Code of Conduct: /code-of-conduct
menuFooter:
  The Camp: /the-camp
  Speakers: /speakers
  Sponsors: /sponsors
  Organisers: /organisers
  Contact: /contact
  Diversity & Inclusiveness: /diversity-and-inclusiveness
  Code of Conduct: /code-of-conduct

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
